# Output running with: `./run_kubernetes.sh`
Error from server (AlreadyExists): pods "udacity-pj4" already exists
NAME          READY   STATUS    RESTARTS   AGE
udacity-pj4   1/1     Running   0          5m38s
Forwarding from 127.0.0.1:8000 -> 80
Forwarding from [::1]:8000 -> 80
Handling connection for 8000

# Output running with: `kubectl logs udacity-pj4`
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 952-115-617
[2022-08-26 15:03:05,400] INFO in app: JSON payload: 
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-08-26 15:03:05,415] INFO in app: Inference payload DataFrame: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-26 15:03:05,425] INFO in app: Scaling Payload: 
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-08-26 15:03:05,429] INFO in app: Prediction: 
[20.35373177134412]
127.0.0.1 - - [26/Aug/2022 15:03:05] "POST /predict HTTP/1.1" 200 -